apiVersion: v2
name: monitoring
description: Monitoring stack
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: prometheus
    version: 25.27.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: jaeger
    version: 3.3.1
    repository: https://jaegertracing.github.io/helm-charts
    condition: jaeger.enabled
  - name: loki
    version: 6.16.0
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled
  - name: grafana
    version: 8.5.5
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled