services:
  admin-api:
    build:
      context: .
      dockerfile: ./backend/admin-api/Dockerfile
    container_name: admin-api
    ports:
      - "8080:8080"
    environment:
      - ENV=local
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      scylla-init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

  scraper-api:
    build:
      context: .
      dockerfile: ./backend/scraper-api/Dockerfile
    container_name: scraper-api
    ports:
      - "5001:5001"
    environment:
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001"]
      interval: 30s
      timeout: 10s
      retries: 3

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: ./frontend/Dockerfile
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     api:
  #       condition: service_healthy
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:5173"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

  postgres:
    image: postgres:16.4-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  scylla:
    image: scylladb/scylla:6.1.2
    command: 
      - --smp 1
      - --memory 750M
    volumes:
      - ./infra/docker/scylla/:/scylla_init/
    ports:
      - "9042:9042"
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 30s
      timeout: 10s
      retries: 5

  scylla-init:
    image: scylladb/scylla:6.1.2
    volumes:
      - ./infra/docker/scylla/:/scylla_init/
    entrypoint: "/scylla_init/init.sh"
    depends_on:
      scylla:
        condition: service_healthy
  
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.111.0
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./infra/docker/otel/otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - 4317:4317
      - 4318:4318

  prometheus:
    image: prom/prometheus:v2.54.1
    volumes:
      - ./infra/docker/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  jaeger:
    image: jaegertracing/all-in-one:1.62.0
    ports:
      - 16686:16686
  
  tempo:
    image: grafana/tempo:2.6.1
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./infra/docker/tempo/tempo.yaml:/etc/tempo.yaml
    ports:
      - "14268"
      - "3200"
      - "4317"
      - "4318"
      - "9411"
  
  loki:
    image: grafana/loki:3.2.0
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./infra/docker/loki/loki-config.yaml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: "postgresql://user:password@postgres:5432/admin?sslmode=disable"
    links:
      - postgres
      - prometheus
  
  pyroscope:
    image: grafana/pyroscope:1.9.0
    ports:
    - 4040:4040

  grafana:
    image: grafana/grafana:11.2.2
    restart: always
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_INSTALL_PLUGINS=redis-datasource,grafana-lokiexplore-app,grafana-exploretraces-app,grafana-pyroscope-app
    volumes:
      - ./infra/docker/grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"

volumes:
  postgres_data:
