services:
  postgres:
    image: postgres:16.4-alpine
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d myapp"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: ./frontend/Dockerfile
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     api:
  #       condition: service_healthy
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:5173"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  
  api:
    build:
      context: .
      dockerfile: ./backend/admin-api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV=local
      - Auth0ClientID=
      - Auth0ClientSecret=
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      scylla-init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

  scylla:
    image: scylladb/scylla:6.1.2
    command: 
      - --smp 1
      - --memory 750M
    volumes:
      - ./infra/docker/scylla/:/scylla_init/
    ports:
      - "9042:9042"
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 30s
      timeout: 10s
      retries: 5

  scylla-init:
    image: scylladb/scylla:6.1.2
    volumes:
      - ./infra/docker/scylla/:/scylla_init/
    entrypoint: "/scylla_init/init.sh"
    depends_on:
      scylla:
        condition: service_healthy

volumes:
  postgres_data: