server:
  address: ":8080"
  env: "prod"

postgres:
  url: "postgresql://user:password@postgres:5432/admin"

scylla:
  hosts:
    - "scylla:9042"
  keyspace: "scraper_metadata"

redis:
  address: "redis:6379"

auth0:
  domain: "dev-dp4vp0xpt7cspfcl.us.auth0.com"
  audience: "https://scrapmaster.com/api/login"

otel:
  endpoint: "otel-collector:4317"
  endpointhttp: "otel-collector:4318"
  pyroscopeurl: "http://pyroscope:4040"

cors:
  allowOrigins:
    - "http://localhost:5173"
