server:
  address: ":8080"

postgres:
  url: "postgresql://user:password@postgres:5432/myapp"

scylla:
  hosts:
    - "scylla:9042"
  keyspace: "crawltask_keyspace"

redis:
  address: "redis:6379"

auth0:
  domain: "dev-dp4vp0xpt7cspfcl.us.auth0.com"
  audience: "https://scrapmaster.com/api/login"
