global:
  environment: production

loki:
  enabled: true
  singleBinary:
    replicas: 3
  ingester:
    chunk_encoding: snappy
  tracing:
    enabled: true
  querier:
    max_concurrent: 4
  loki:
    auth_enabled: true
    storage:
      type: s3
    storage_config:
      aws:
        s3: s3://loki-prod-storage-bucket
        bucketnames: loki-prod-storage-bucket
        region: us-west-2  # Replace with your AWS region
      boltdb_shipper:
        active_index_directory: /loki/boltdb-shipper-active
        cache_location: /loki/boltdb-shipper-cache
        cache_ttl: 24h
        shared_store: s3
    schema_config:
      configs:
        - from: "2024-04-01"
          store: boltdb-shipper
          object_store: s3
          schema: v12
          index:
            prefix: loki_index_
            period: 24h
    compactor:
      working_directory: /loki/boltdb-shipper-compactor
      shared_store: s3

grafana:
  adminPassword: