apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy 
    orgId: 1
    uid: loki
    url: http://loki:3100
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: jaeger
          matcherRegex: "\"traceid\":\s?\"([0-9a-fA-F]+)\""  # Updated regex to match traceid
          name: TraceID
          url: '$${__value.raw}'
          urlDisplayLabel: 'View Trace'