apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy 
    orgId: 1
    uid: loki
    url: http://loki:3100
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    
    jsonData:
      derivedFields:
        - datasourceUid: loki
          matcherRegex: "\"traceid\":\\s?\"([0-9a-fA-F]+)\""
          name: TraceID
          url: '$${__value.raw}'
          urlDisplayLabel: 'View Trace'
