apiVersion: 1

datasources:
  - name: Postgres
    type: grafana-postgresql-datasource
    url: postgres:5432
    user: user
    secureJsonData:
      password: 'password'
    jsonData:
      database: admin
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false