apiVersion: 1

datasources:
  - name: Redis
    uid: redis
    type: redis-datasource
    access: proxy
    orgId: 1
    version: 1
    url: redis://host.docker.internal:6379
    jsonData:
      client: standalone
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0
    editable: true
