apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    version: 1
    editable: false
    apiVersion: 1
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
      streamingEnabled:
        search: true
